name: Common
main: Common\Main
version: 1.1.0
api: 3.0.0

author: Eric
description: Convenience Commands/Events

permissions:
  common.tpo:
    description: Permission for /tpo
    default: op
  common.gms:
    description: Permission for /tpo
    default: op
  common.gmc:
    description: Permission for /tpo
    default: op
  common.gma:
    description: Permission for /tpo
    default: op
  common.gmspc:
    description: Permission for /tpo
    default: op